# Generated by Django 5.2.1 on 2025-07-07 08:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('budget', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming'), ('in_production', 'In Production')], default='released', max_length=20)),
                ('adult', models.BooleanField(default=False)),
                ('popularity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vote_average', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vote_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='genres_name_4778a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'movie_genres',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, through='movies.MovieGenre', to='movies.genre'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('profile_image_url', models.URLField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='people_name_1a4b17_idx'), models.Index(fields=['imdb_id'], name='people_imdb_id_855b72_idx'), models.Index(fields=['tmdb_id'], name='people_tmdb_id_38ba32_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'movie_crew',
                'ordering': ['department', 'job'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('cast_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'movie_cast',
                'ordering': ['cast_order'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies_as_cast', through='movies.MovieCast', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='movies_as_crew', through='movies.MovieCrew', to='movies.person'),
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('origin_country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Production Companies',
                'db_table': 'production_companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='production__name_f5c957_idx'), models.Index(fields=['origin_country'], name='production__origin__abc5a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieProductionCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.productioncompany')),
            ],
            options={
                'db_table': 'movie_production_companies',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(blank=True, through='movies.MovieProductionCompany', to='movies.productioncompany'),
        ),
        migrations.AddIndex(
            model_name='moviegenre',
            index=models.Index(fields=['movie'], name='movie_genre_movie_i_011b21_idx'),
        ),
        migrations.AddIndex(
            model_name='moviegenre',
            index=models.Index(fields=['genre'], name='movie_genre_genre_i_d5ee0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together={('movie', 'genre')},
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['movie'], name='movie_crew_movie_i_da40fc_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['person'], name='movie_crew_person__5b9e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['job'], name='movie_crew_job_6f817f_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['department'], name='movie_crew_departm_58252b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'job')},
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['movie'], name='movie_cast_movie_i_acd6db_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['person'], name='movie_cast_person__a6785d_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['cast_order'], name='movie_cast_cast_or_58900e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('movie', 'person')},
        ),
        migrations.AddIndex(
            model_name='movieproductioncompany',
            index=models.Index(fields=['movie'], name='movie_produ_movie_i_80b82b_idx'),
        ),
        migrations.AddIndex(
            model_name='movieproductioncompany',
            index=models.Index(fields=['company'], name='movie_produ_company_d8c2e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='movieproductioncompany',
            unique_together={('movie', 'company')},
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_title_179e04_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['original_title'], name='movies_origina_97f733_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_release_e1d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status'], name='movies_status_da1881_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['imdb_id'], name='movies_imdb_id_7ab72f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_tmdb_id_472987_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_featured'], name='movies_is_feat_541cef_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity_score'], name='movies_popular_b4c926_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average'], name='movies_vote_av_b71f90_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created_at'], name='movies_created_f9b5f9_idx'),
        ),
    ]
